<<<<<<< HEAD

## 현재 이슈
- GCS 버킷 접근 권한 설정 : `storage.buckets.list` 권한 부여하기
	- TPU에서 GCS 버킷에 접근할 권한을 부여해야 하는 것 같다.

## 230907
- 코랩에서 TPU로 학습하려면 GCS 관련 설정도 필요한 듯 하다. 그거 진행 중..
- GCS 버킷 접근 권한 설정 : `storage.buckets.list` 권한 부여하기
	- `[service-495559152420@cloud-tpu.iam.gserviceaccount.com](mailto:service-495559152420@cloud-tpu.iam.gserviceaccount.com) does not have storage.objects.list access to the Google Cloud Storage bucket.` 인걸로 봐서는 TPU에서 버킷에 접근할 권한을 부여해야 하는 것 같다.

## 230904
- 계속 같은 이슈 : `learning_rate` 인식 관련.
	- 상속받는 클래스 문제였나? `class AdamWeightDecayOptimizer(tf.compat.v1.train.Optimizer):`로 수정하니까 넘어가지긴 했음.
	- 여전히 **`init_lr` 값이 텐서에 전달되지 않는 문제**는 있음!
=======
## 현재 이슈
```
ValueError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on gs://your-bucket-name/models/char_ranked: 
PERMISSION_DENIED: Error executing an HTTP request: HTTP response code 403 with body '{ "error": { "code": 403, "message": "[dowrave@gmail.com](mailto:dowrave@gmail.com) does not have storage.objects.list access to the Google Cloud Storage bucket. 
Permission 'storage.objects.list' denied on resource (or it may not exist).", "errors": [ { "message": "[dowrave@gmail.com](mailto:dowrave@gmail.com) does not have storage.objects.list access to the Google Cloud Storage bucket. 
Permission 'storage.objects.list' denied on resource (or it may not exist).", "domain": "global", "reason": "forbidden" ' when reading gs://your-bucket-name/models
```
- 대충 요런 내용이다.


## 230906
### 새로운 이슈
- `UNIMPLEMENTED: File system scheme '[local]' not implemented (file: './models/char_ranked/model.ckpt-2000000')` 에러
	- GCS Bucket을 써라 + TPU가 해당 GCS Bucket에 접근할 수 있어야 한다
		- GCS 체험판(3달간 300$ 무료)을 사용해봄
	- 혹은, 캐글의 TPU를 사용하는 방법도 있다.
	- GCS 버킷 세팅 & 파일 업로드 완료, 코랩 파일에도 연동 완료.
### 이슈 2
## 230904 
- 이슈 해결 : 상속받는 optimzer를 `keras`가 아니라 `tf.compat.v1`에서 받게끔 변경
>>>>>>> 8a3937219ad46c1a1613e1db9835d5e1dbe7af54

## 230901
- 멀고도 험하다. `krBERT`를 `Tensorflow 2.X` 버전에서 실행하기..

### 이슈
1. `learning_rate`를 `optimization.create_optimizer`에서 인식하지 못하는 이슈

- 이해가 안 가는 상황이다.
```python
# main.py
import tensorflow as tf

lr = 5e-5
print(lr) # 5e-05

tensor = tf.compat.v1.constant(value = lr, shape = [], dtype = tf.compat.v1.float32)
print(tensor) # tf.Tensor(5e-05, shape=(), dtype=float32)
```

- 위 상황에서, lr 값을 `optimization.py`에 전달한 다음 아래 함수에 전달하는 상황임.
```python
# optimization.py
import tensorflow.compat.v1 as tf
import tensorflow
from tensorflow import keras

def create_optimizer(loss, init_lr, num_train_steps, num_warmup_steps, use_tpu):
  """Creates an optimizer training op."""
  global_step = tf.train.get_or_create_global_step()

  print("init_lr : ", init_lr)
  learning_rate = tf.constant(value=init_lr, shape=[], dtype=tf.float32)

  print("tensor : ", learning_rate)

  # Implements linear decay of the learning rate.
  learning_rate = tf.train.polynomial_decay(
      learning_rate,
      global_step,
      num_train_steps,
      end_learning_rate=0.0,
      power=1.0,
      cycle=False)
    
  print("polynomial_decay : ", learning_rate)

# ....
```

- 근데 여기서 `main.py`에서 `init_lr` 값을 `5e-5`로 전달했을 때,
```python
  print("init_lr : ", init_lr) # 5e-05
  print("tensor : ", learning_rate) # Tensor("Const:0", shape=(), dtype=float32)
  print("polynomial_decay : ", learning_rate) # Tensor("PolynomialDecay:0", shape=(), dtype=float32)

```
- 왜 이렇게 나오는지 모르겠음.

